### ISSUE TITLE
Module crashing on invalid certificate

### ISSUE THREAD

**Issue by lindskogen** [breach/mod_strip#17]
Visiting https://chalmers.it (my student union site) which doesn't have a valid SSL-certificate crashes `mod_strip` entirely, here's the output:

```
[2014-07-10T20:54:58.539Z] ERROR: unable to verify the first certificate
[2014-07-10T20:54:58.540Z] Error: unable to verify the first certificate
[2014-07-10T20:54:58.540Z]     at Error (native)
[2014-07-10T20:54:58.540Z]     at TLSSocket.<anonymous> (_tls_wrap.js:906:36)
[2014-07-10T20:54:58.540Z]     at TLSSocket.EventEmitter.emit (events.js:104:17)
[2014-07-10T20:54:58.540Z]     at TLSSocket._finishInit (_tls_wrap.js:457:8)
[2014-07-10T20:54:58.540Z] ---------------------------------------------
```

**Comment by spolu** [comment]
Definitely marking this one as a bug. Thanks for reporting that!

**Comment by markbahnman** [comment]
I get the same issue, it also locks up the strip and the inspector.

![breach_error](https://cloud.githubusercontent.com/assets/197497/3545820/313dbb3a-087b-11e4-8eb8-0fa108556404.png)

There also isn't an obvious way to reset the data that mod_strip caches. I tried removing and reinstalling it, as well as removing and reinstalling Breach but it still saves my previous tabs triggering the error again.

**Comment by lindskogen** [comment]
A workaround is to use keyboard shortcuts to close the tab with the error and then reloading the module!

**Comment by spolu** [comment]
The data is stored in 

OSX:
`~/Library/Application Support/breach/gig.fs/modules/modules\:mod_strip\:tabs/`

Linux
`~/.breach/gig.fs/modules/modules\:mod_strip\:tabs/`

You can remove the entire directory and relaunch Breach
