### ISSUE TITLE
Tabs race issue

### ISSUE THREAD

**Issue by spolu** [breach/mod_strip#4]
When opening a tab, loading an URL (tabs_new), after the first navigation, the tabs may return to its original URL (tabs_load_url), which should not be possible.

Here's two example:

```
[2014-06-27T20:43:26.497Z] [tabs] tabs_show __NEW_TAB_ID__
[2014-06-27T20:43:28.678Z] [box] submit_url https://www.google.com/search?q=mdn%20split&ie=UTF-8
[2014-06-27T20:43:28.694Z] [tabs] tabs_new dfbac4e21913e85335f8de37c18db9705038652f [https://www.google.com/search?q=mdn%20split&ie=UTF-8]
[2014-06-27T20:43:28.694Z] [tabs] tabs_show dfbac4e21913e85335f8de37c18db9705038652f
[2014-06-27T20:43:31.259Z] [tabs] tabs_load_url dfbac4e21913e85335f8de37c18db9705038652f [https://www.google.com/search?q=mdn%20split&ie=UTF-8]
[2014-06-27T20:43:37.481Z] [tabs] tabs_show __NEW_TAB_ID__
[2014-06-27T20:44:22.783Z] [box] submit_url https://www.google.com/search?q=test&ie=UTF-8
[2014-06-27T20:44:22.800Z] [tabs] tabs_new 157471ee5c0b7058832dad57cddcd44825b32504 [https://www.google.com/search?q=test&ie=UTF-8]
[2014-06-27T20:44:22.801Z] [tabs] tabs_show 157471ee5c0b7058832dad57cddcd44825b32504
[2014-06-27T20:44:24.374Z] [tabs] tabs_show __NEW_TAB_ID__
[2014-06-27T20:44:56.985Z] [tabs] tabs_show 157471ee5c0b7058832dad57cddcd44825b32504
[2014-06-27T20:44:59.423Z] [tabs] tabs_load_url 157471ee5c0b7058832dad57cddcd44825b32504 [https://www.google.com/search?q=test&ie=UTF-8]
```

**Comment by spolu** [comment]
Another maybe related issue: 

```
2014-06-27T20:33:33.212Z] [tabs] tabs_show 1743852ceb58ab2c5c61ec9a02a6fed58461df79
[2014-06-27T20:33:33.238Z] [tabs] tabs_new 1743852ceb58ab2c5c61ec9a02a6fed58461df79 [https://www.google.com/search?q=find%20similar%20substrings&ie=UTF-8]
[2014-06-27T20:33:33.280Z] *********************************************
[2014-06-27T20:33:33.280Z] *********************************************
[2014-06-27T20:33:33.283Z] ---------------------------------------------
[2014-06-27T20:33:33.280Z] ERROR: Tab `id` already exists: 1743852ceb58ab2c5c61ec9a02a6fed58461df79
[2014-06-27T20:33:33.283Z] Error: Tab `id` already exists: 1743852ceb58ab2c5c61ec9a02a6fed58461df79
[2014-06-27T20:33:33.283Z]     at Object.exports.err (/home/spolu/src/breach/mod_layout/node_modules/breach_module/lib/common.js:264:13)
[2014-06-27T20:33:33.283Z]     at handle_message (/home/spolu/src/breach/mod_layout/node_modules/breach_module/lib/module.js:217:26)
[2014-06-27T20:33:33.283Z]     at process.<anonymous> (/home/spolu/src/breach/mod_layout/node_modules/breach_module/lib/module.js:267:7)
[2014-06-27T20:33:33.283Z]     at process.EventEmitter.emit (events.js:110:17)
[2014-06-27T20:33:33.283Z]     at handleMessage (child_process.js:323:10)
[2014-06-27T20:33:33.283Z]     at Pipe.channel.onread (child_process.js:351:11)
```

**Comment by spolu** [comment]
With load info

```
[2014-06-27T20:52:01.437Z] [box] submit_url https://www.google.com/search?q=test&ie=UTF-8
[2014-06-27T20:52:01.440Z] [tabs] action_load 5b1bcf90f3148e68ae0c749e2df0c082f74421f5 [https://www.google.com/search?q=test&ie=UTF-8]
[2014-06-27T20:52:01.450Z] [tabs] tabs_new 5b1bcf90f3148e68ae0c749e2df0c082f74421f5 [https://www.google.com/search?q=test&ie=UTF-8] 2
[2014-06-27T20:52:01.452Z] [tabs] tabs_show 5b1bcf90f3148e68ae0c749e2df0c082f74421f5
[2014-06-27T20:52:04.406Z] [tabs] tabs_load_url 5b1bcf90f3148e68ae0c749e2df0c082f74421f5 [https://www.google.com/search?q=test&ie=UTF-8] 0 < 2
[2014-06-27T20:52:05.677Z] [tabs] tabs_show __NEW_TAB_ID__
```
